// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xvktwwchaizjqjvtkwwb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh2a3R3d2NoYWl6anFqdnRrd3diIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1OTc0NTksImV4cCI6MjA3MTE3MzQ1OX0.A-KNBhpVhpuMrBJGzg_VT0aNOrK-t82yxSj5Y4ncMho";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});